#!/usr/bin/env python3
"""Generate traditional actuarial triangle visualizations for the demo.

The script intentionally uses only the Python standard library. It reads the
CSV triangles generated by `scripts/generate_demo_triangles.py` and creates:

- SVG visualizations for MkDocs;
- Markdown tables in traditional actuarial triangle format.
"""

from __future__ import annotations

import argparse
import csv
import html
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class TriangleSpec:
    language: str
    source_csv: Path
    origin_column: str
    output_svg: Path
    output_markdown: Path
    title: str
    subtitle: str
    table_title: str
    origin_label: str
    dev_label: str
    observed_label: str
    diagonal_label: str
    future_label: str
    value_unit_label: str


SPECS: tuple[TriangleSpec, ...] = (
    TriangleSpec(
        language="es",
        source_csv=ROOT / "data/demo_triangulos/triangulo_pagado_acumulado.csv",
        origin_column="anio_origen",
        output_svg=ROOT / "docs/assets/demo_triangulos/triangulo_pagado_acumulado.svg",
        output_markdown=ROOT / "data/demo_triangulos/triangulo_pagado_acumulado_formato_actuarial.md",
        title="Triángulo pagado acumulado",
        subtitle="Estructura actuarial tradicional: año de origen × edad de desarrollo",
        table_title="Triángulo pagado acumulado en formato actuarial",
        origin_label="Año origen",
        dev_label="Edad de desarrollo",
        observed_label="Observado",
        diagonal_label="Última diagonal observada",
        future_label="No observado / futuro",
        value_unit_label="Valores en miles de millones",
    ),
    TriangleSpec(
        language="es",
        source_csv=ROOT / "data/demo_triangulos/triangulo_pagado_incremental.csv",
        origin_column="anio_origen",
        output_svg=ROOT / "docs/assets/demo_triangulos/triangulo_pagado_incremental.svg",
        output_markdown=ROOT / "data/demo_triangulos/triangulo_pagado_incremental_formato_actuarial.md",
        title="Triángulo pagado incremental",
        subtitle="Pagos incrementales observados por año de origen y edad de desarrollo",
        table_title="Triángulo pagado incremental en formato actuarial",
        origin_label="Año origen",
        dev_label="Edad de desarrollo",
        observed_label="Observado",
        diagonal_label="Última diagonal observada",
        future_label="No observado / futuro",
        value_unit_label="Valores en miles de millones",
    ),
    TriangleSpec(
        language="en",
        source_csv=ROOT / "data/demo_triangles/paid_cumulative_triangle.csv",
        origin_column="origin_year",
        output_svg=ROOT / "docs/assets/demo_triangles/paid_cumulative_triangle.svg",
        output_markdown=ROOT / "data/demo_triangles/paid_cumulative_triangle_actuarial_format.md",
        title="Paid cumulative triangle",
        subtitle="Traditional actuarial structure: origin year × development age",
        table_title="Paid cumulative triangle in actuarial format",
        origin_label="Origin year",
        dev_label="Development age",
        observed_label="Observed",
        diagonal_label="Latest observed diagonal",
        future_label="Unobserved / future",
        value_unit_label="Values in billions",
    ),
    TriangleSpec(
        language="en",
        source_csv=ROOT / "data/demo_triangles/paid_incremental_triangle.csv",
        origin_column="origin_year",
        output_svg=ROOT / "docs/assets/demo_triangles/paid_incremental_triangle.svg",
        output_markdown=ROOT / "data/demo_triangles/paid_incremental_triangle_actuarial_format.md",
        title="Paid incremental triangle",
        subtitle="Observed incremental payments by origin year and development age",
        table_title="Paid incremental triangle in actuarial format",
        origin_label="Origin year",
        dev_label="Development age",
        observed_label="Observed",
        diagonal_label="Latest observed diagonal",
        future_label="Unobserved / future",
        value_unit_label="Values in billions",
    ),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate SVG and Markdown visual actuarial triangles for the demo."
    )
    parser.add_argument(
        "--language",
        choices=("es", "en", "both"),
        default="both",
        help="Language outputs to generate. Default: both.",
    )
    return parser.parse_args()


def selected_specs(language: str) -> Iterable[TriangleSpec]:
    for spec in SPECS:
        if language == "both" or spec.language == language:
            yield spec


def read_triangle(spec: TriangleSpec) -> tuple[list[str], list[tuple[str, list[float | None]]]]:
    if not spec.source_csv.exists():
        raise FileNotFoundError(
            f"Missing source CSV: {spec.source_csv.relative_to(ROOT)}. "
            "Run `python scripts/generate_demo_triangles.py` first."
        )

    with spec.source_csv.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {spec.source_csv}")

        dev_columns = [name for name in reader.fieldnames if name.startswith("dev_")]
        rows: list[tuple[str, list[float | None]]] = []

        for raw in reader:
            values: list[float | None] = []
            for column in dev_columns:
                text = (raw.get(column) or "").strip()
                values.append(float(text) if text else None)
            rows.append((str(raw[spec.origin_column]), values))

    return dev_columns, rows


def compact_amount(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value / 1_000_000_000:.1f}"


def full_amount(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value:,.0f}"


def latest_observed(values: list[float | None]) -> int | None:
    for index in range(len(values) - 1, -1, -1):
        if values[index] is not None:
            return index
    return None


def write_markdown_table(
    spec: TriangleSpec,
    dev_columns: list[str],
    rows: list[tuple[str, list[float | None]]],
) -> None:
    spec.output_markdown.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        f"# {spec.table_title}",
        "",
        f"{spec.value_unit_label}. Las celdas vacías corresponden a periodos no observados en la diagonal actual."
        if spec.language == "es"
        else f"{spec.value_unit_label}. Blank cells correspond to periods not observed as of the current diagonal.",
        "",
        "| " + spec.origin_label + " | " + " | ".join(dev_columns) + " |",
        "| " + " | ".join(["---"] * (len(dev_columns) + 1)) + " |",
    ]

    for origin, values in rows:
        rendered = [full_amount(value) for value in values]
        lines.append("| " + origin + " | " + " | ".join(rendered) + " |")

    lines.extend(
        [
            "",
            "> Nota: esta tabla mantiene la estructura triangular tradicional usada en reserving actuarial."
            if spec.language == "es"
            else "> Note: this table preserves the traditional triangular structure used in actuarial reserving.",
            "",
        ]
    )
    spec.output_markdown.write_text("\n".join(lines), encoding="utf-8")


def svg_text(x: int, y: int, text: str, *, size: int = 12, weight: str = "400", anchor: str = "middle") -> str:
    safe = html.escape(text)
    return (
        f'<text x="{x}" y="{y}" text-anchor="{anchor}" '
        f'font-size="{size}" font-weight="{weight}" fill="#111827">{safe}</text>'
    )


def write_svg(
    spec: TriangleSpec,
    dev_columns: list[str],
    rows: list[tuple[str, list[float | None]]],
) -> None:
    spec.output_svg.parent.mkdir(parents=True, exist_ok=True)

    cell_width = 84
    cell_height = 42
    left_margin = 118
    top_margin = 132
    right_margin = 48
    bottom_margin = 76
    title_y = 34
    subtitle_y = 58

    width = left_margin + len(dev_columns) * cell_width + right_margin
    height = top_margin + len(rows) * cell_height + bottom_margin

    observed_fill = "#DBEAFE"
    diagonal_fill = "#BBF7D0"
    future_fill = "#F3F4F6"
    grid_stroke = "#CBD5E1"
    header_fill = "#EEF2FF"
    text_color = "#111827"
    muted = "#6B7280"

    parts: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-label="{html.escape(spec.title)}">',
        "<defs>",
        "<style>",
        "text { font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }",
        ".cell-value { font-size: 11px; fill: #111827; }",
        ".axis-label { font-size: 12px; fill: #374151; font-weight: 600; }",
        ".header { font-size: 11px; fill: #111827; font-weight: 700; }",
        ".muted { font-size: 11px; fill: #6B7280; }",
        "</style>",
        "</defs>",
        f'<rect x="0" y="0" width="{width}" height="{height}" fill="#FFFFFF"/>',
        svg_text(24, title_y, spec.title, size=20, weight="700", anchor="start"),
        f'<text x="24" y="{subtitle_y}" text-anchor="start" font-size="13" fill="{muted}">{html.escape(spec.subtitle)}</text>',
        f'<text x="24" y="{subtitle_y + 22}" text-anchor="start" font-size="12" fill="{muted}">{html.escape(spec.value_unit_label)}</text>',
    ]

    # Axis label.
    parts.append(
        f'<text x="{left_margin + (len(dev_columns) * cell_width) // 2}" y="{top_margin - 44}" '
        f'class="axis-label" text-anchor="middle">{html.escape(spec.dev_label)}</text>'
    )
    parts.append(
        f'<text x="22" y="{top_margin + (len(rows) * cell_height) // 2}" '
        f'class="axis-label" text-anchor="middle" transform="rotate(-90 22 {top_margin + (len(rows) * cell_height) // 2})">{html.escape(spec.origin_label)}</text>'
    )

    # Column headers.
    parts.append(
        f'<rect x="{left_margin}" y="{top_margin - cell_height}" width="{len(dev_columns) * cell_width}" height="{cell_height}" fill="{header_fill}" stroke="{grid_stroke}"/>'
    )
    for col_index, column in enumerate(dev_columns):
        x = left_margin + col_index * cell_width
        parts.append(
            f'<rect x="{x}" y="{top_margin - cell_height}" width="{cell_width}" height="{cell_height}" fill="transparent" stroke="{grid_stroke}"/>'
        )
        parts.append(
            f'<text x="{x + cell_width / 2:.0f}" y="{top_margin - 16}" class="header" text-anchor="middle">{html.escape(column)}</text>'
        )

    # Row headers and cells.
    for row_index, (origin, values) in enumerate(rows):
        y = top_margin + row_index * cell_height
        diagonal_index = latest_observed(values)

        parts.append(
            f'<rect x="{left_margin - 82}" y="{y}" width="82" height="{cell_height}" fill="{header_fill}" stroke="{grid_stroke}"/>'
        )
        parts.append(
            f'<text x="{left_margin - 41}" y="{y + 26}" class="header" text-anchor="middle">{html.escape(origin)}</text>'
        )

        for col_index, value in enumerate(values):
            x = left_margin + col_index * cell_width
            if value is None:
                fill = future_fill
                rendered_value = "—"
                value_class = "muted"
            elif diagonal_index == col_index:
                fill = diagonal_fill
                rendered_value = compact_amount(value)
                value_class = "cell-value"
            else:
                fill = observed_fill
                rendered_value = compact_amount(value)
                value_class = "cell-value"

            parts.append(
                f'<rect x="{x}" y="{y}" width="{cell_width}" height="{cell_height}" fill="{fill}" stroke="{grid_stroke}"/>'
            )
            parts.append(
                f'<text x="{x + cell_width / 2:.0f}" y="{y + 26}" class="{value_class}" text-anchor="middle">{html.escape(rendered_value)}</text>'
            )

    # Legend.
    legend_y = height - 42
    legend_x = left_margin
    legend_items = [
        (observed_fill, spec.observed_label),
        (diagonal_fill, spec.diagonal_label),
        (future_fill, spec.future_label),
    ]
    offset = 0
    for color, label in legend_items:
        parts.append(
            f'<rect x="{legend_x + offset}" y="{legend_y}" width="16" height="16" fill="{color}" stroke="{grid_stroke}"/>'
        )
        parts.append(
            f'<text x="{legend_x + offset + 22}" y="{legend_y + 13}" font-size="11" fill="{text_color}">{html.escape(label)}</text>'
        )
        offset += 218 if spec.language == "es" else 202

    parts.append("</svg>")
    spec.output_svg.write_text("\n".join(parts), encoding="utf-8")


def generate(spec: TriangleSpec) -> None:
    dev_columns, rows = read_triangle(spec)
    write_markdown_table(spec, dev_columns, rows)
    write_svg(spec, dev_columns, rows)


def main() -> None:
    args = parse_args()
    print("=== Visual actuarial triangle demo ===")

    generated = 0
    for spec in selected_specs(args.language):
        generate(spec)
        generated += 1
        print(f"OK: {spec.output_svg.relative_to(ROOT)}")
        print(f"OK: {spec.output_markdown.relative_to(ROOT)}")

    print(f"Generated visual triangles: {generated}")


if __name__ == "__main__":
    main()
